### ISSUE TITLE
交流一下

### ISSUE THREAD

**Issue by Danjuanlab** [kfitfk/dynamic-lottie-glyph#1]
你好，我在lottie-web中看到了你的贴子，也看了你的博客学到了些新的知识。我自己也有在使用lottie来制作一些可交互的动画。我使用的是SVG来呈现，并且在输出的时候不将文字转换成路径。当在网页端加载动画的时候就会默认的套用字体，同时可以使用JS来更新这部分文字的内容。你可以看看我的贴子，里面有写关于如何使用JS来更新文本的，不知道对你是不是有帮助。https://www.ui.cn/detail/495919.html

**Comment by kfitfk** [comment]
你好，我在你文章里第一次发现 lottie-api 这个库，以后有相关需求可以试验一下。其实 lottie-web 的 SVG 渲染器是对动画支持最好的，不管是对 AE 效果的还原还是对前端的友好度。像支付宝前端时间推的那个[犸良](https://design.alipay.com/emotion)平台就是基于 lottie SVG 渲染器的，文案处理比起 canvas 省事太多。我的场景要保证服务端和浏览器渲染一致性，基于 canvas 来做最方便，开发到中期才发现 lottie canvas 处理文案的局限性。到这个阶段，比起换方案来说，我觉得能绕过这个问题更好。

**Comment by Danjuanlab** [comment]
嗯，canvas的方案你已经能搞定没必要换方案。因为我是用lottie来制作可交互的直播特效，所以我才用我上面说的方案，因为不需要考虑太多端。不过canvas处理简单的文字动画可以，但是如果文字有比较复杂的animator可能就不是很好解决了（猜测），因为在这样的情况下你还需要计算关键帧数据而不是单是文字路径数据了。而且如果有文字切分动画，那每个文字相当于是一个独立层。
https://lottiefiles.com/9015-flip-coin
例如我做的这个动画中，硬币上的文字也是可以更换内容，但是这样的运动下，canvas应该很难实现把。应为我也没有用canvas做过案例，还希望多多交流把。我有个lottie技术的交流群，如果有兴趣可以加群，qq群719027079。

**Comment by kfitfk** [comment]
glyph 是这样的，导出之后会把这个字符的绘图属性记录下来，至于动画复杂程度，是和文案图层的结构相关，所以两者是分开两个数据结构。我们目前还没有做过需要 morph 文本路径节点的复杂动画，不清楚是不是能导出来。如果文字都是独立图层，只要能用基础的 transform 属性做出来，理论上不影响 canvas/svg 渲染器的还原效果。不过你那个是 3D 的喔，你可以试试把导出的时候带上 glyph 和 demo 选项，再把 demo 里的 renderer 改成 canvas 验证下。

你是设计师吗？我来围观一下大家都怎么用这个东西。这条我先关掉了。
