### ISSUE TITLE
Dynamic Text (http://blog.kfitfk.me/programming/2019/11/24/char-outline.html)

### ISSUE THREAD

**Issue by roimulia2** [kfitfk/dynamic-lottie-glyph#2]
Loved the article! 

Is it doable to achieve full dynamic text for iOS with this approach? 

Thanks!

**Comment by kfitfk** [comment]
I don't do iOS development using Swift or Objective-C. I'm not sure whether you need glyph data on iOS. According to [this doc](http://airbnb.io/lottie/#/supported-features), it says that glyphs are not supported on iOS. Though I'm not sure if the glyph is what I mean in my blog.

I did a little search and saw that you were following [this issue](https://github.com/airbnb/lottie-ios/issues/1191). Good luck!

**Comment by roimulia2** [comment]
Thank you for the reply! Any chance we can do a quick call? We are facing some issues unrelated to iOS, it's with the overall work structure of Lottie. Even 5 min chat will save us ton of time

**Comment by kfitfk** [comment]
Closing inactive issue
