### ISSUE TITLE
text glyph problem

### ISSUE THREAD

**Issue by ruidianliu** [kfitfk/dynamic-lottie-glyph#3]
Hi, I have readed your artical, and try to run your code, But it's only half done.
I try to change text '1235', but i got this:
![image](https://user-images.githubusercontent.com/31526404/218386140-7df8cb82-44a8-48d6-85d9-111026f781f0.png)
I don‘t know what should i do，I would appreciate it if you could help me.

**Comment by kfitfk** [comment]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/2555626/218402189-37f067f2-fad3-48ac-8074-72faa844a171.png">
The demo works fine for me (by locking fontkit to 1.8.0). You got any additional setups?

**Comment by ruidianliu** [comment]
Thank you for your answer,use fontkit to 1.8.0, it works, then how to use Chinese character? 
![image](https://user-images.githubusercontent.com/31526404/218413082-eb531366-d22e-4083-ab8f-d7642c0482a5.png)

**Comment by kfitfk** [comment]
1. Replace the font that comes with the demo with any Chinese font file;
2. Update the `fonts` and text layer's `f` property of the lottie JSON file with the correct font info. It'll be much easier that you export a new lottie JSON file from After Effects using the desired font.

**Comment by ruidianliu** [comment]
Thank you very much, you've been most helpful
